### ISSUE TITLE
Bad encoding GUI translation Polish Language 

### ISSUE THREAD

**Issue by FadeMind** [steganos-oss/locknote2#1]
This is bad
![20230821-1692626630](https://github.com/steganos-oss/locknote2/assets/9846948/c65e52dd-c14a-4d7a-92d0-71a6dac7e782)
![20230821-1692626623](https://github.com/steganos-oss/locknote2/assets/9846948/b00018b8-e754-47d5-bae4-f3d55e2068f5)
![20230821-1692626610](https://github.com/steganos-oss/locknote2/assets/9846948/b7e5f2f8-afbd-4900-8cdb-ac0e47b5e925)
instead of polish specify letters weird marks.

**Comment by steganos-oss** [comment]
Thank you for your feedback, we've fixed this in version 2.0.1, released today. Please try it again if you like.
